# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('where_heard_abt_us', models.CharField(choices=[('blog', 'Blog'), ('website', 'Website'), ('advert', 'Advertisement'), ('social_media', 'Social Media')], default='advert', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
