# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('ad_reference', models.CharField(
                    choices=[('blog', 'Blog'), ('website', 'Website'), ('advert', 'Advertisement'),
                             ('social_media', 'Social Media')], default='advert', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
