# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='user',
            new_name='owner',
        ),
    ]
