# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161107_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
