# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscriptionplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_no',
            new_name='user_phone_no',
        ),
    ]
