# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161107_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(upload_to='company_brouchure/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=10)),
                ('certification_description', models.CharField(blank=True, default=None, max_length=200)),
                ('certification_doc', models.FileField(blank=True, default=None, upload_to='certification/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=40)),
                ('address_line2', models.CharField(blank=True, default=None, max_length=40)),
                ('address_line3', models.CharField(blank=True, default=None, max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('pin_code', models.CharField(max_length=6)),
                ('website', models.CharField(blank=True, default=None, max_length=200)),
                ('year_founded', models.CharField(blank=True, default=None, max_length=200)),
                ('about', models.CharField(blank=True, default=None, max_length=100)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(default=None, upload_to='company_gallery/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_clients', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default=None, upload_to='comapany_logo/')),
                ('registration_no', models.CharField(blank=True, default=None, max_length=12)),
                ('bio', models.CharField(blank=True, default=None, max_length=1000)),
                ('no_of_emp', models.IntegerField(blank=True, default=None)),
                ('sale_volume', models.CharField(blank=True, default=None, max_length=30)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('S', 'Super Premium')], default='BSC', max_length=3)),
                ('sub_begin_time', models.DateField(default=None)),
                ('sub_end_time', models.DateField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('S', 'Super Premium')], max_length=4, unique=True)),
                ('cost_per_month', models.FloatField()),
                ('discount', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
