# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161103_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
