# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161108_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='certification_description',
            new_name='certi_description',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='certification_doc',
            new_name='certi_doc',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='certification_name',
            new_name='certi_name',
        ),
        migrations.RenameField(
            model_name='freefields',
            old_name='pin_code',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery',
            new_name='image',
        ),
    ]
