# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161108_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freefields',
            name='address_line1',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
