# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161108_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certi_name',
            field=models.CharField(max_length=100),
        ),
    ]
