# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161108_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='ad_reference',
            field=models.CharField(choices=[('B', 'Blog'), ('W', 'Website'), ('A', 'Advertisement'), ('S', 'Social Media'), ('O', 'Other')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='company_phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='freefields',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='freefields',
            name='pin',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='company_gallery/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='premiumfields',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='comapany_logo/'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='linkedin',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
