# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161108_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PremiumFields',
            new_name='BasicPremiumFields',
        ),
    ]
