# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161109_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpremiumfields',
            name='bio',
        ),
        migrations.AlterField(
            model_name='basicpremiumfields',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='company_logo/'),
        ),
    ]
