# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161109_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certi_doc',
            field=models.FileField(blank=True, default=None, upload_to='company_certification/'),
        ),
    ]
